DATANAME="ERA5"
START=200001
END=200012

LATNAME="latitude"
LONNAME="longitude"

# For each variable, specify level with unit (e.g. "850hPa", "85000Pa")
# Leave empty if single-level data

MSLP_DIR="/huracan/tank4/cornell/ORCESTRA/era5/mean_sea_level_pressure"
MSLP="sp"
MSLP_LEVEL=""
MSLP_TRES="6h"
MSLP_UNIT="Pa"

Z850_DIR="/huracan/tank4/cornell/ORCESTRA/era5/geopotential"
Z850="z"
Z850_LEVEL="850hPa"
Z850_TRES="6h"
#"m2s-2" or "m"
Z850_UNIT="m2s-2" 


Z300_DIR="/huracan/tank4/cornell/ORCESTRA/era5/geopotential"
Z300="z"
Z300_LEVEL="300hPa"
Z300_TRES="6h"
#"m2s-2" or "m"
Z300_UNIT="m2s-2" 

Z500_DIR="/huracan/tank4/cornell/ORCESTRA/era5/geopotential"
Z500="z"
Z500_LEVEL="500hPa"
Z500_TRES="6h"
#"m2s-2" or "m"
Z500_UNIT="m2s-2" 


# If rv850 data do not exist, Fill u850 and v850
RV850_DIR=""
RV850=""
RV850_LEVEL=""
RV850_TRES=""
U850_DIR="/huracan/tank4/cornell/ORCESTRA/era5/u_component_of_wind"
U850="u"
U850_LEVEL="850hPa"
U850_TRES="6h"
V850_DIR="/huracan/tank4/cornell/ORCESTRA/era5/v_component_of_wind"
V850="v"
V850_LEVEL="850hPa"
V850_TRES="6h"

R850_DIR="/huracan/tank4/cornell/ORCESTRA/era5/relative_humidity"
R850="r"
R850_LEVEL="850hPa"
R850_TRES="6h"
# "fraction" or "%"
R850_UNIT="%" 

U10_DIR="/huracan/tank4/cornell/ORCESTRA/era5/10m_u_component_of_wind"
U10="u10"
U10_LEVEL=""
U10_TRES="6h"

V10_DIR="/huracan/tank4/cornell/ORCESTRA/era5/10m_v_component_of_wind"
V10="v10"
V10_LEVEL=""
V10_TRES="6h"

ZS_DIR="/huracan/tank4/cornell/ORCESTRA/era5/ERA5_sfc_geopotential.nc"
ZS="zs"
ZS_LEVEL=""
ZS_TRES=""
# "m" or "m2s-2"
ZS_UNIT="m2s-2" 

RH_THRESHOLD=75.0
