DATANAME="ERA5"
START=202408
END=202409

LATNAME="latitude"
LONNAME="longitude"

# For each variable, specify level with unit (e.g. "850hPa", "85000Pa")
# Leave empty if single-level data

MSLP_DIR="/huracan/tank4/cornell/ORCESTRA/era5/mean_sea_level_pressure/202408"
MSLP="sp"
MSLP_LEVEL=""
MSLP_TRES="1h"
MSLP_UNIT="Pa"

Z850_DIR="/huracan/tank4/cornell/ORCESTRA/era5/geopotential/202408"
Z850="z"
Z850_LEVEL="850hPa"
Z850_TRES="1h"
#"m2s-2" or "m"
Z850_UNIT="m2s-2" 


Z300_DIR="/huracan/tank4/cornell/ORCESTRA/era5/geopotential/202408"
Z300="z"
Z300_LEVEL="300hPa"
Z300_TRES="1h"
#"m2s-2" or "m"
Z300_UNIT="m2s-2" 

Z500_DIR="/huracan/tank4/cornell/ORCESTRA/era5/geopotential/202408"
Z500="z"
Z500_LEVEL="500hPa"
Z500_TRES="1h"
#"m2s-2" or "m"
Z500_UNIT="m2s-2" 


# If rv850 data do not exist, Fill u850 and v850
RV850_DIR=""
RV850=""
RV850_LEVEL=""
RV850_TRES=""
U850_DIR="/huracan/tank4/cornell/ORCESTRA/era5/u_component_of_wind/202408"
U850="u"
U850_LEVEL="850hPa"
U850_TRES="1h"
V850_DIR="/huracan/tank4/cornell/ORCESTRA/era5/v_component_of_wind/202408"
V850="v"
V850_LEVEL="850hPa"
V850_TRES="1h"

# If r850 data do not exist, Fill t850 and q850
R850_DIR=""
R850=""
R850_LEVEL=""
R850_TRES=""
# "fraction" or "%"
R850_UNIT="%"
T850_DIR="/huracan/tank4/cornell/ORCESTRA/era5/temperature/202408"
T850="t"
T850_LEVEL="850hPa"
T850_TRES="1h"
Q850_DIR="/huracan/tank4/cornell/ORCESTRA/era5/specific_humidity/202408"
Q850="q"
Q850_LEVEL="850hPa"
Q850_TRES="1h" 

U10_DIR="/huracan/tank4/cornell/ORCESTRA/era5/10m_u_component_of_wind/202408"
U10="u10"
U10_LEVEL=""
U10_TRES="1h"

V10_DIR="/huracan/tank4/cornell/ORCESTRA/era5/10m_v_component_of_wind/202408"
V10="v10"
V10_LEVEL=""
V10_TRES="1h"

ZS_DIR="/huracan/tank4/cornell/ORCESTRA/era5/sfc_geopotential/ERA5_sfc_geopotential.nc"
ZS="zs"
ZS_LEVEL=""
ZS_TRES="1h"
# "m" or "m2s-2"
ZS_UNIT="m2s-2" 

RH_THRESHOLD=75.0
