DATANAME="ERA5"
START=198001
END=202512

LATNAME="latitude"
LONNAME="longitude"

# For each variable, specify level with unit (e.g. "850hPa", "85000Pa")
# Leave empty if single-level data

MSLP_DIR="/data09/ERA5/hourly/sp"
MSLP="sp"
MSLP_LEVEL=""
MSLP_TRES="6h"
MSLP_UNIT="Pa"

Z850_DIR="/data09/ERA5/hourly/z"
Z850="z"
Z850_LEVEL="850hPa"
Z850_TRES="6h"
#"m2s-2" or "m"
Z850_UNIT="m2s-2" 

Z300_DIR="/data09/ERA5/hourly/z"
Z300="z"
Z300_LEVEL="300hPa"
Z300_TRES="6h"
#"m2s-2" or "m"
Z300_UNIT="m2s-2" 

Z500_DIR="/data09/ERA5/hourly/z"
Z500="z"
Z500_LEVEL="500hPa"
Z500_TRES="6h"
#"m2s-2" or "m"
Z500_UNIT="m2s-2" 


# If rv850 data do not exist, Fill u850 and v850
RV850_DIR="/data09/ERA5/hourly/vo"
RV850="vo"
RV850_LEVEL="850hPa"
RV850_TRES="6h"
U850_DIR=""
U850=""
U850_LEVEL=""
U850_TRES=""
V850_DIR=""
V850=""
V850_LEVEL=""
V850_TRES=""

R850_DIR="/data09/ERA5/hourly/r"
R850="r"
R850_LEVEL="850hPa"
R850_TRES="6h"
# "fraction" or "%"
R850_UNIT="%" 

U10_DIR="/data09/ERA5/hourly/10u"
U10="u10"
U10_LEVEL=""
U10_TRES="6h"

V10_DIR="/data09/ERA5/hourly/10v"
V10="v10"
V10_LEVEL=""
V10_TRES="6h"

ZS_DIR="/data09/ERA5_modified/invariant_0p25/zs_0p25.nc"
ZS="zs"
ZS_LEVEL=""
ZS_TRES=""
# "m" or "m2s-2"
ZS_UNIT="m2s-2" 

RH_THRESHOLD=75.0
