DATANAME="MERRA2"
START=202501
END=202501

LATNAME="lat"
LONNAME="lon"

# For each variable, specify level with unit (e.g. "850hPa", "85000Pa")
# Leave empty if single-level data

MSLP_DIR="/home1/jhmoon/data/MERRA2/pres6h"
MSLP="SLP"
MSLP_LEVEL=""
MSLP_TRES="6h"
MSLP_UNIT="Pa"

Z850_DIR="/home1/jhmoon/data/MERRA2/pres6h"
Z850="H"
Z850_LEVEL="850hPa"
Z850_TRES="6h"
#"m2s-2" or "m"
Z850_UNIT="m" 

Z500_DIR="/home1/jhmoon/data/MERRA2/pres6h"
Z500="H"
Z500_LEVEL="500hPa"
Z500_TRES="6h"
#"m2s-2" or "m"
Z500_UNIT="m" 

Z300_DIR="/home1/jhmoon/data/MERRA2/pres6h"
Z300="H"
Z300_LEVEL="300hPa"
Z300_TRES="6h"
#"m2s-2" or "m"
Z300_UNIT="m" 

# Leave empty if rv850 data do not exist, Fill u850 and v850
RV850_DIR=""
RV850=""
RV850_LEVEL=""
RV850_TRES=""
U850_DIR="/home1/jhmoon/data/MERRA2/pres6h"
U850="U"
U850_LEVEL="850hPa"
U850_TRES="6h"
V850_DIR="/home1/jhmoon/data/MERRA2/pres6h"
V850="V"
V850_LEVEL="850hPa"
V850_TRES="6h"

R850_DIR="/home1/jhmoon/data/MERRA2/pres3h"
R850="RH"
R850_LEVEL="850hPa"
R850_TRES="3h"
# "fraction" or "%"
R850_UNIT="fraction" 

U10_DIR="/home1/jhmoon/data/MERRA2/single1h"
U10="U10M"
U10_LEVEL=""
U10_TRES="1h"

V10_DIR="/home1/jhmoon/data/MERRA2/single1h"
V10="V10M"
V10_LEVEL=""
V10_TRES="1h"

ZS_DIR="/home1/jhmoon/data/MERRA2/pres3h"
ZS="PHIS"
ZS_LEVEL=""
ZS_TRES="3h"
# "m" or "hPa"
ZS_UNIT="m"

RH_THRESHOLD=75.0
